[toolchain]
anchor_version = "0.32.1"
solana_version = "2.3.0"

[features]
resolution = true
skip-lint = false

[programs.devnet]
solarma_vault = "F54LpWS97bCvkn5PGfUsFi8cU8HyYBZgyozkSkAbAjzP"

[programs.localnet]
solarma_vault = "F54LpWS97bCvkn5PGfUsFi8cU8HyYBZgyozkSkAbAjzP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["."]

[scripts]
test = "npm run test:fast"

[test]
startup_wait = 30000
